#!/usr/bin/env bash
# install Nginx on a server
sudo apt-get update
sudo apt-get -y install nginx
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo echo "Hello World!" > /var/www/html/index.html

