#!/usr/bin/env bash
# install Nginx on a server
sudo apt-get -y install nginx
sudo sed -i 'listen/[0-9]*/s/[0-9]*/80/' /etc/nginx/sites-enabled/default
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html

